version: "3.7"

services:
  app:
    build: ./app
    container_name: api_mock.app
    command: uvicorn main:app --reload --host 0.0.0.0
    working_dir: /app
    environment:
      - TZ=Asia/Tokyo
      - PYTHONPATH=/app:/db
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
